name: Update README cards

on:
  schedule:
    - cron: "0 */12 * * *" # Runs every 12 hours
  workflow_dispatch: # Allows manual testing

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate Stats Card
        uses: lowlighter/metrics@latest
        with:
          filename: profile/stats.svg
          token: ${{ secrets.GH_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Africa/Cairo
          config_order: base.header, base.activity, base.community, base.repositories

      - name: Generate Top Languages Card
        uses: lowlighter/metrics@latest
        with:
          filename: profile/top-langs.svg
          token: ${{ secrets.GH_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_details: bytes-compact, percentage
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
